import 'dart:convert';
import 'package:sqflite/sqflite.dart';
import 'package:path/path.dart';
import 'package:path_provider/path_provider.dart';
import 'package:uuid/uuid.dart';
import 'dart:io';

class DatabaseHelper {
  static final DatabaseHelper _instance = DatabaseHelper._internal();
  factory DatabaseHelper() => _instance;
  DatabaseHelper._internal();

  static Database? _database;
  static const Uuid _uuid = Uuid();
  static const Set<String> _autoGeneratedTextIdTables = {
    'users',
    'orders',
    'order_assignments',
    'order_status_logs',
    'products',
    'materials',
    'equipment',
    'customers',
    'supplier_materials',
    'branches',
    'suppliers',
    'properties',
    'tenants',
    'rent_payments',
    'rent_dues',
    'landlord_payments',
    'landlord_dues',
    'social_accounts',
    'social_metrics',
    'purchase_orders',
    'purchase_order_items',
    'fuel_logs',
    'maintenance_logs',
    'checkout_logs',
    'commissions',
    'accounts',
    'transactions',
    'payment_transaction',
    'payment_breakdown',
    'measurement_types',
    'measurements',
    'production_orders',
    'employee_payments',
    'leave_requests',
    'losses',
    'material_usage',
    'pending_deletions',
  };
  static const List<String> _syncTrackedTables = [
    'roles',
    'users',
    'orders',
    'material_usage',
    'products',
    'materials',
    'equipment',
    'customers',
    'branches',
    'suppliers',
    'properties',
    'tenants',
    'rent_payments',
    'rent_dues',
    'landlord_payments',
    'landlord_dues',
    'social_accounts',
    'social_metrics',
    'purchase_orders',
    'purchase_order_items',
    'fuel_logs',
    'maintenance_logs',
    'checkout_logs',
    'commissions',
    'accounts',
    'transactions',
    'payment_transaction',
    'payment_breakdown',
    'order_assignments',
    'order_status_logs',
    'measurement_types',
    'measurements',
    'production_orders',
    'employee_payments',
    'leave_requests',
    'losses',
  ];
  static const Set<String> _excludedChangedFields = {
    'syncStatus',
    'lastModified',
    'changed_fields',
    'paid_amount',
  };

  Future<Database> get database async {
    if (_database != null) return _database!;
    _database = await _initDatabase();
    return _database!;
  }

  Future<Database> _initDatabase() async {
    Directory documentsDirectory = await getApplicationDocumentsDirectory();
    String path = join(documentsDirectory.path, 'semere_fashions.db');
    return await openDatabase(
      path,
      version: 41, // Bump database version
      onCreate: _onCreate,
      onUpgrade: _onUpgrade,
      onOpen: (db) async {
        await _ensureChangedFieldsColumns(db);
      },
    );
  }

  Future<void> _ensureChangedFieldsColumns(Database db) async {
    for (final table in _syncTrackedTables) {
      try {
        await db.execute('ALTER TABLE $table ADD COLUMN changed_fields TEXT');
      } catch (_) {
        // Column or table may already exist on upgraded installs.
      }
    }
  }

  Future<void> _ensureConflictColumns(Database db) async {
    try {
      await db.execute(
        'ALTER TABLE conflicts ADD COLUMN conflictingFields TEXT',
      );
    } catch (_) {
      // Existing installs may already have this column.
    }
  }

  Future<void> _seedDefaultRoles(Database db) async {
    final now = DateTime.now().millisecondsSinceEpoch;
    const roleNames = ['Admin', 'Manager', 'Sales', 'Tailor', 'Delivery'];
    for (final roleName in roleNames) {
      await db.insert('roles', {
        'name': roleName,
        'salary_type': 'commission',
        'default_monthly_salary': null,
        'created_at': now,
        'syncStatus': 'pending',
        'lastModified': now,
        'changed_fields': jsonEncode({
          'name': roleName,
          'salary_type': 'commission',
          'default_monthly_salary': null,
          'created_at': now,
        }),
      }, conflictAlgorithm: ConflictAlgorithm.ignore);
    }
  }

  Future<void> ensureDefaultRoles() async {
    final db = await database;
    final countResult = await db.rawQuery('SELECT COUNT(*) AS count FROM roles');
    final roleCount = (countResult.first['count'] as num?)?.toInt() ?? 0;
    if (roleCount == 0) {
      await _seedDefaultRoles(db);
    }
  }

  Future<void> _migrateToUuidFriendlyIds(Database db) async {
    await db.execute('''
      CREATE TABLE IF NOT EXISTS orders_new(
        id TEXT PRIMARY KEY,
        customerId TEXT,
        customerName TEXT,
        items TEXT,
        totalAmount REAL,
        delivery_fee REAL DEFAULT 0,
        discount_type TEXT,
        discount_value REAL DEFAULT 0,
        status TEXT,
        createdAt INTEGER,
        createdBy TEXT,
        branchId TEXT,
        tailorId TEXT,
        currency TEXT,
        tracking_number TEXT,
        courier_name TEXT,
        salesPersonId TEXT,
        stock_deducted INTEGER DEFAULT 0,
        paid_amount REAL DEFAULT 0,
        cogs REAL DEFAULT 0,
        syncStatus TEXT DEFAULT 'synced',
        lastModified INTEGER,
        changed_fields TEXT
      )
    ''');
    await db.execute('''
      INSERT INTO orders_new SELECT
        CAST(id AS TEXT),
        CAST(customerId AS TEXT),
        customerName,
        items,
        totalAmount,
        delivery_fee,
        discount_type,
        discount_value,
        status,
        createdAt,
        CAST(createdBy AS TEXT),
        CAST(branchId AS TEXT),
        CAST(tailorId AS TEXT),
        currency,
        tracking_number,
        courier_name,
        CAST(salesPersonId AS TEXT),
        stock_deducted,
        paid_amount,
        cogs,
        syncStatus,
        lastModified,
        changed_fields
      FROM orders
    ''');
    await db.execute('DROP TABLE orders');
    await db.execute('ALTER TABLE orders_new RENAME TO orders');

    await db.execute('''
      CREATE TABLE IF NOT EXISTS order_assignments_new(
        id TEXT PRIMARY KEY,
        orderId TEXT,
        employeeId TEXT,
        employeeName TEXT,
        employeePhone TEXT,
        role TEXT,
        assignedAt INTEGER,
        commission_amount REAL DEFAULT 0,
        syncStatus TEXT DEFAULT 'synced',
        lastModified INTEGER,
        changed_fields TEXT
      )
    ''');
    await db.execute('''
      INSERT INTO order_assignments_new SELECT
        CAST(id AS TEXT),
        CAST(orderId AS TEXT),
        CAST(employeeId AS TEXT),
        employeeName,
        NULL,
        role,
        assignedAt,
        commission_amount,
        syncStatus,
        lastModified,
        changed_fields
      FROM order_assignments
    ''');
    await db.execute('DROP TABLE order_assignments');
    await db.execute(
      'ALTER TABLE order_assignments_new RENAME TO order_assignments',
    );

    await db.execute('''
      CREATE TABLE IF NOT EXISTS payment_transaction_new(
        id TEXT PRIMARY KEY,
        orderId TEXT,
        branchId TEXT,
        receivedBy TEXT,
        date INTEGER,
        type TEXT,
        amount REAL DEFAULT 0,
        tip_amount REAL DEFAULT 0,
        deletedAt INTEGER DEFAULT 0,
        syncStatus TEXT DEFAULT 'synced',
        lastModified INTEGER,
        changed_fields TEXT
      )
    ''');
    await db.execute('''
      INSERT INTO payment_transaction_new SELECT
        CAST(id AS TEXT),
        CAST(orderId AS TEXT),
        CAST(branchId AS TEXT),
        CAST(receivedBy AS TEXT),
        date,
        type,
        amount,
        tip_amount,
        deletedAt,
        syncStatus,
        lastModified,
        changed_fields
      FROM payment_transaction
    ''');
    await db.execute('DROP TABLE payment_transaction');
    await db.execute(
      'ALTER TABLE payment_transaction_new RENAME TO payment_transaction',
    );

    await db.execute('''
      CREATE TABLE IF NOT EXISTS payment_breakdown_new(
        id TEXT PRIMARY KEY,
        payment_transaction_id TEXT,
        method TEXT,
        amount REAL,
        account_id TEXT,
        syncStatus TEXT DEFAULT 'synced',
        lastModified INTEGER,
        changed_fields TEXT
      )
    ''');
    await db.execute('''
      INSERT INTO payment_breakdown_new SELECT
        CAST(id AS TEXT),
        CAST(payment_transaction_id AS TEXT),
        method,
        amount,
        CAST(account_id AS TEXT),
        syncStatus,
        lastModified,
        changed_fields
      FROM payment_breakdown
    ''');
    await db.execute('DROP TABLE payment_breakdown');
    await db.execute(
      'ALTER TABLE payment_breakdown_new RENAME TO payment_breakdown',
    );

    await db.execute('''
      CREATE TABLE IF NOT EXISTS commissions_new(
        id TEXT PRIMARY KEY,
        orderId TEXT,
        employeeId TEXT,
        employeeName TEXT,
        amount REAL,
        type TEXT,
        status TEXT DEFAULT 'pending',
        createdAt INTEGER,
        paidAt INTEGER,
        syncStatus TEXT DEFAULT 'synced',
        lastModified INTEGER,
        changed_fields TEXT
      )
    ''');
    await db.execute('''
      INSERT INTO commissions_new SELECT
        CAST(id AS TEXT),
        CAST(orderId AS TEXT),
        CAST(employeeId AS TEXT),
        employeeName,
        amount,
        type,
        status,
        createdAt,
        paidAt,
        syncStatus,
        lastModified,
        changed_fields
      FROM commissions
    ''');
    await db.execute('DROP TABLE commissions');
    await db.execute('ALTER TABLE commissions_new RENAME TO commissions');
  }

  Future _onUpgrade(Database db, int oldVersion, int newVersion) async {
    if (oldVersion < 24) {
      await db.execute(
        'ALTER TABLE materials ADD COLUMN cost_per_unit REAL DEFAULT 0',
      );
      await db.execute('''
        CREATE TABLE material_usage(
          id TEXT PRIMARY KEY,
          material_id TEXT,
          quantity REAL,
          cost REAL,
          date INTEGER,
          notes TEXT,
          syncStatus TEXT DEFAULT 'synced',
          lastModified INTEGER
        )
      ''');
    }
    if (oldVersion < 25) {
      await db.execute(
        'ALTER TABLE payment_transaction ADD COLUMN tip_amount REAL DEFAULT 0',
      );
    }
    if (oldVersion < 2) {
      await db.execute('''
        CREATE TABLE measurement_types(
          id TEXT PRIMARY KEY,
          name TEXT,
          unit TEXT,
          sortOrder INTEGER,
          syncStatus TEXT DEFAULT 'synced',
          lastModified INTEGER
        )
      ''');
      await db.execute('''
        CREATE TABLE measurements(
          id TEXT PRIMARY KEY,
          customer_id TEXT,
          measurement_type_id TEXT,
          date_taken INTEGER,
          value REAL,
          notes TEXT,
          order_id TEXT,
          syncStatus TEXT DEFAULT 'synced',
          lastModified INTEGER
        )
      ''');
    }
    // In database_helper.dart
    if (oldVersion < 23) {
      await db.execute('ALTER TABLE orders ADD COLUMN cogs REAL DEFAULT 0');
    }
    if (oldVersion < 3) {
      await db.execute('''
        CREATE TABLE accounts(
          id TEXT PRIMARY KEY,
          name TEXT,
          type TEXT,
          opening_balance REAL,
          current_balance REAL,
          notes TEXT,
          syncStatus TEXT DEFAULT 'synced',
          lastModified INTEGER
        )
      ''');
      await db.execute('''
        CREATE TABLE transactions(
          id TEXT PRIMARY KEY,
          account_id TEXT,
          date INTEGER,
          amount REAL,
          type TEXT,
          category TEXT,
          reference_id TEXT,
          description TEXT,
          status TEXT,
          syncStatus TEXT DEFAULT 'synced',
          lastModified INTEGER
        )
      ''');
    }
    if (oldVersion < 4) {
      await db.execute(
        'ALTER TABLE orders ADD COLUMN delivery_fee REAL DEFAULT 0',
      );
      await db.execute(
        'ALTER TABLE users ADD COLUMN delivery_commission_type TEXT',
      );
      await db.execute(
        'ALTER TABLE users ADD COLUMN delivery_commission_value REAL DEFAULT 0',
      );
      await db.execute('''
        CREATE TABLE order_assignments(
          id TEXT PRIMARY KEY,
          orderId TEXT,
          employeeId TEXT,
          employeeName TEXT,
          role TEXT,
          assignedAt INTEGER,
          syncStatus TEXT DEFAULT 'synced',
          lastModified INTEGER
        )
      ''');
    }
    if (oldVersion < 5) {
      await db.execute('ALTER TABLE orders ADD COLUMN discount_type TEXT');
      await db.execute(
        'ALTER TABLE orders ADD COLUMN discount_value REAL DEFAULT 0',
      );
    }
    if (oldVersion < 6) {
      await db.execute('''
        CREATE TABLE production_orders(
          id TEXT PRIMARY KEY,
          productName TEXT,
          tailorId TEXT,
          tailorName TEXT,
          materialsUsed TEXT,
          totalMaterialCost REAL,
          tailorCommission REAL,
          totalCost REAL,
          sellingPrice REAL DEFAULT 0,
          status TEXT,
          createdAt INTEGER,
          completedAt INTEGER,
          notes TEXT,
          syncStatus TEXT DEFAULT 'synced',
          lastModified INTEGER
        )
      ''');
      await db.execute(
        'ALTER TABLE products ADD COLUMN productionOrderId TEXT',
      );
    }
    if (oldVersion < 7) {
      await db.execute(
        'ALTER TABLE order_assignments ADD COLUMN commission_amount REAL DEFAULT 0',
      );
    }
    if (oldVersion < 8) {
      await db.execute(
        'ALTER TABLE equipment ADD COLUMN registration_expiry INTEGER',
      );
      await db.execute(
        'ALTER TABLE equipment ADD COLUMN insurance_policy TEXT',
      );
      await db.execute(
        'ALTER TABLE equipment ADD COLUMN insurance_expiry INTEGER',
      );
    }
    if (oldVersion < 9) {
      await db.execute('''
        CREATE TABLE supplier_materials(
          id TEXT PRIMARY KEY,
          supplierId TEXT,
          materialId TEXT,
          notes TEXT,
          syncStatus TEXT DEFAULT 'synced',
          lastModified INTEGER
        )
      ''');
    }
    if (oldVersion < 10) {
      await db.execute('''
        CREATE TABLE employee_payments(
          id TEXT PRIMARY KEY,
          employeeId TEXT,
          employeeName TEXT,
          type TEXT,
          amount REAL,
          month TEXT,
          datePaid INTEGER,
          notes TEXT,
          syncStatus TEXT DEFAULT 'synced',
          lastModified INTEGER
        )
      ''');
    }
    if (oldVersion < 11) {
      await db.execute('''
        CREATE TABLE leave_requests(
          id TEXT PRIMARY KEY,
          employeeId TEXT,
          employeeName TEXT,
          startDate INTEGER,
          endDate INTEGER,
          reason TEXT,
          status TEXT DEFAULT 'pending',
          approvedBy TEXT,
          approvedAt INTEGER,
          notes TEXT,
          syncStatus TEXT DEFAULT 'synced',
          lastModified INTEGER
        )
      ''');
    }
    if (oldVersion < 12) {
      await db.execute(
        'ALTER TABLE branches ADD COLUMN currency TEXT DEFAULT "ETB"',
      );
    }
    if (oldVersion < 13) {
      await db.execute('ALTER TABLE orders ADD COLUMN currency TEXT');
    }
    if (oldVersion < 14) {
      await db.execute('ALTER TABLE users ADD COLUMN fcmToken TEXT');
    }
    if (oldVersion < 15) {
      await db.execute('ALTER TABLE materials ADD COLUMN createdAt INTEGER');
      await db.execute('ALTER TABLE products ADD COLUMN createdAt INTEGER');
    }
    if (oldVersion < 16) {
      await db.execute('''
        CREATE TABLE pending_deletions(
          id TEXT PRIMARY KEY,
          tableName TEXT,
          recordId TEXT,
          timestamp INTEGER
        )
      ''');
    }
    if (oldVersion < 17) {
      await db.execute('ALTER TABLE orders ADD COLUMN tracking_number TEXT');
      await db.execute('ALTER TABLE orders ADD COLUMN courier_name TEXT');
    }
    if (oldVersion < 18) {
      await db.execute('ALTER TABLE orders ADD COLUMN salesPersonId TEXT');
    }
    if (oldVersion < 19) {
      await db.execute('''
        CREATE TABLE payment_transaction(
          id TEXT PRIMARY KEY,
          orderId TEXT,
          branchId TEXT,
          receivedBy TEXT,
          date INTEGER,
          type TEXT,
          deletedAt INTEGER DEFAULT 0,
          syncStatus TEXT DEFAULT 'synced',
          lastModified INTEGER
        )
      ''');
      await db.execute('''
        CREATE TABLE payment_breakdown(
          id TEXT PRIMARY KEY,
          payment_transaction_id TEXT,
          method TEXT,
          amount REAL,
          syncStatus TEXT DEFAULT 'synced',
          lastModified INTEGER
        )
      ''');
    }
    if (oldVersion < 20) {
      await db.execute(
        'ALTER TABLE orders ADD COLUMN stock_deducted INTEGER DEFAULT 0',
      );
    }
    if (oldVersion < 21) {
      await db.execute(
        'ALTER TABLE orders ADD COLUMN paid_amount REAL DEFAULT 0',
      );
    }
    if (oldVersion < 22) {
      await db.execute(
        'ALTER TABLE payment_transaction ADD COLUMN amount REAL DEFAULT 0',
      );
    }
    if (oldVersion < 30) {
      try {
        await db.execute(
          'ALTER TABLE payment_transaction ADD COLUMN deletedAt INTEGER DEFAULT 0',
        );
      } catch (_) {}
    }
    if (oldVersion < 31) {
      await db.execute('''
        CREATE TABLE IF NOT EXISTS roles(
          id INTEGER PRIMARY KEY AUTOINCREMENT,
          name TEXT NOT NULL UNIQUE,
          salary_type TEXT NOT NULL DEFAULT 'commission',
          default_monthly_salary REAL,
          created_at INTEGER,
          syncStatus TEXT DEFAULT 'synced',
          lastModified INTEGER,
          changed_fields TEXT
        )
      ''');
      try {
        await db.execute(
          'ALTER TABLE users ADD COLUMN role_id INTEGER REFERENCES roles(id)',
        );
      } catch (_) {}
      try {
        await db.execute('ALTER TABLE users ADD COLUMN monthly_salary REAL');
      } catch (_) {}
      try {
        await db.execute(
          'ALTER TABLE employee_payments ADD COLUMN for_month TEXT',
        );
      } catch (_) {}
      try {
        await db.execute(
          'ALTER TABLE employee_payments ADD COLUMN status TEXT DEFAULT "paid"',
        );
      } catch (_) {}
      try {
        await db.execute(
          'ALTER TABLE employee_payments ADD COLUMN createdAt INTEGER',
        );
      } catch (_) {}
      await _seedDefaultRoles(db);
    }
    if (oldVersion < 26) {
      await _ensureChangedFieldsColumns(db);
      await _ensureConflictColumns(db);
    }
    if (oldVersion < 27) {
      await _ensureConflictColumns(db);
      await db.execute('ALTER TABLE users ADD COLUMN device_id TEXT');
      await db.execute('''
        CREATE TABLE IF NOT EXISTS dashboard_cache (
          key TEXT PRIMARY KEY,
          value TEXT,
          lastUpdated INTEGER
        )
      ''');
    }
    if (oldVersion < 28) {
      try {
        await db.execute('ALTER TABLE accounts ADD COLUMN branchId TEXT');
      } catch (_) {}
      try {
        await db.execute(
          'ALTER TABLE payment_breakdown ADD COLUMN account_id TEXT',
        );
      } catch (_) {}
    }
    if (oldVersion < 29) {
      try {
        await db.execute('ALTER TABLE material_usage ADD COLUMN orderId TEXT');
      } catch (_) {}
      try {
        await db.execute(
          'ALTER TABLE material_usage ADD COLUMN type TEXT DEFAULT "order"',
        );
      } catch (_) {}
      try {
        await db.execute(
          'ALTER TABLE products ADD COLUMN is_custom INTEGER DEFAULT 0',
        );
      } catch (_) {}
      await db.execute('''
        CREATE TABLE IF NOT EXISTS losses(
          id TEXT PRIMARY KEY,
          date INTEGER,
          type TEXT,
          amount REAL,
          reason TEXT,
          orderId TEXT,
          syncStatus TEXT DEFAULT 'synced',
          lastModified INTEGER
        )
      ''');
    }
    if (oldVersion < 32) {
      await _migrateToUuidFriendlyIds(db);
    }
    if (oldVersion < 33) {
      try {
        await db.execute(
          "ALTER TABLE properties ADD COLUMN usageType TEXT DEFAULT 'rented_out'",
        );
      } catch (_) {}
      try {
        await db.execute(
          """
          UPDATE properties
          SET usageType = 'business_use'
          WHERE ownership = 'leased'
            AND id NOT IN (
              SELECT propertyId FROM tenants
              WHERE propertyId IS NOT NULL AND propertyId != ''
            )
          """,
        );
      } catch (_) {}
    }
    if (oldVersion < 34) {
      await db.execute('''
        CREATE TABLE IF NOT EXISTS landlord_payments(
          id TEXT PRIMARY KEY,
          propertyId TEXT,
          landlordName TEXT,
          amount REAL,
          month TEXT,
          paidAt INTEGER,
          notes TEXT,
          syncStatus TEXT DEFAULT 'synced',
          lastModified INTEGER,
          changed_fields TEXT
        )
      ''');
      try {
        await db.execute(
          'ALTER TABLE properties ADD COLUMN rentalExpenseType TEXT',
        );
      } catch (_) {}
      try {
        await db.execute(
          'ALTER TABLE properties ADD COLUMN mortgageBank TEXT',
        );
      } catch (_) {}
      try {
        await db.execute(
          'ALTER TABLE properties ADD COLUMN mortgageMonthly REAL',
        );
      } catch (_) {}
    }
    if (oldVersion < 35) {
      await db.execute('''
        CREATE TABLE IF NOT EXISTS landlord_dues(
          id TEXT PRIMARY KEY,
          propertyId TEXT,
          propertyName TEXT,
          landlordName TEXT,
          amount REAL,
          dueMonth TEXT,
          dueDate INTEGER,
          status TEXT,
          createdAt INTEGER,
          syncStatus TEXT DEFAULT 'synced',
          lastModified INTEGER,
          changed_fields TEXT
        )
      ''');
    }
    if (oldVersion < 36) {
      await db.execute('''
        CREATE TABLE IF NOT EXISTS order_status_logs(
          id TEXT PRIMARY KEY,
          orderId TEXT NOT NULL,
          status TEXT NOT NULL,
          changedBy TEXT NOT NULL,
          changedAt INTEGER NOT NULL,
          note TEXT,
          syncStatus TEXT DEFAULT 'pending',
          lastModified INTEGER,
          changed_fields TEXT,
          FOREIGN KEY (orderId) REFERENCES orders(id)
        )
      ''');
    }
    if (oldVersion < 37) {
      try {
        await db.execute('ALTER TABLE roles ADD COLUMN createdAt INTEGER');
      } catch (_) {}
      try {
        await db.execute('ALTER TABLE users ADD COLUMN branch TEXT');
      } catch (_) {}
    }
    if (oldVersion < 38) {
      try {
        await db.execute(
          'ALTER TABLE order_assignments ADD COLUMN employeePhone TEXT',
        );
      } catch (_) {}
      try {
        await db.execute(
          'ALTER TABLE supplier_materials ADD COLUMN changed_fields TEXT',
        );
      } catch (_) {}
    }
    if (oldVersion < 39) {
      try {
        await db.execute("ALTER TABLE accounts ADD COLUMN currency TEXT DEFAULT 'ETB'");
      } catch (_) {}
    }
    if (oldVersion < 40) {
      await db.execute('''
        CREATE TABLE IF NOT EXISTS retail_products(
          id TEXT PRIMARY KEY,
          name TEXT NOT NULL,
          description TEXT,
          category TEXT,
          costPrice REAL,
          sellingPrice REAL,
          stock INTEGER DEFAULT 0,
          minimumStock INTEGER DEFAULT 0,
          branchId TEXT,
          tailorId TEXT,
          tailorCommission REAL,
          createdAt INTEGER,
          syncStatus TEXT DEFAULT 'pending',
          lastModified INTEGER,
          changed_fields TEXT
        )
      ''');
    }
  }

  Future _onCreate(Database db, int version) async {
    // Users table

    await db.execute('''
      CREATE TABLE roles(
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT NOT NULL UNIQUE,
        salary_type TEXT NOT NULL DEFAULT 'commission',
        default_monthly_salary REAL,
        created_at INTEGER,
        createdAt INTEGER,
        syncStatus TEXT DEFAULT 'synced',
        lastModified INTEGER,
        changed_fields TEXT
      )
    ''');

    await db.execute('''
      CREATE TABLE users(
        id TEXT PRIMARY KEY,
        name TEXT,
        phone TEXT,
        role TEXT,
        role_id INTEGER REFERENCES roles(id),
        monthly_salary REAL,
        branchId TEXT,
        branch TEXT,
        employmentType TEXT,
        status TEXT,
        commissionRate REAL,
        tailorCut REAL,
        delivery_commission_type TEXT,
        delivery_commission_value REAL DEFAULT 0,
        createdAt INTEGER,
        fcmToken TEXT,
        device_id TEXT,
        syncStatus TEXT DEFAULT 'synced',
        lastModified INTEGER
      )
    ''');

    // Branches table
    await db.execute('''
      CREATE TABLE branches(
        id TEXT PRIMARY KEY,
        name TEXT,
        location TEXT,
        phone TEXT,
        email TEXT,
        currency TEXT DEFAULT 'ETB',
        syncStatus TEXT DEFAULT 'synced',
        lastModified INTEGER
      )
    ''');

    // Orders table (with all fields, no comments)
    await db.execute('''
      CREATE TABLE orders(
        id TEXT PRIMARY KEY,
        customerId TEXT,
        customerName TEXT,
        items TEXT,
        totalAmount REAL,
        delivery_fee REAL DEFAULT 0,
        discount_type TEXT,
        discount_value REAL DEFAULT 0,
        status TEXT,
        createdAt INTEGER,
        createdBy TEXT,
        branchId TEXT,
        tailorId TEXT,
        currency TEXT,
        tracking_number TEXT,
        courier_name TEXT,
        salesPersonId TEXT,
        stock_deducted INTEGER DEFAULT 0,
        paid_amount REAL DEFAULT 0,
        cogs REAL DEFAULT 0,
        syncStatus TEXT DEFAULT 'synced',
        lastModified INTEGER
      )
    ''');

    // Order assignments table
    await db.execute('''
      CREATE TABLE order_assignments(
        id TEXT PRIMARY KEY,
        orderId TEXT,
        employeeId TEXT,
        employeeName TEXT,
        employeePhone TEXT,
        role TEXT,
        assignedAt INTEGER,
        commission_amount REAL DEFAULT 0,
        syncStatus TEXT DEFAULT 'synced',
        lastModified INTEGER
      )
    ''');

    await db.execute('''
      CREATE TABLE order_status_logs(
        id TEXT PRIMARY KEY,
        orderId TEXT NOT NULL,
        status TEXT NOT NULL,
        changedBy TEXT NOT NULL,
        changedAt INTEGER NOT NULL,
        note TEXT,
        syncStatus TEXT DEFAULT 'pending',
        lastModified INTEGER,
        changed_fields TEXT,
        FOREIGN KEY (orderId) REFERENCES orders(id)
      )
    ''');

    // Products table
    await db.execute('''
      CREATE TABLE products(
        id TEXT PRIMARY KEY,
        name TEXT,
        category TEXT,
        costPrice REAL,
        sellingPrice REAL,
        stock INTEGER,
        minimumLevel INTEGER,
        productionOrderId TEXT,
        is_custom INTEGER DEFAULT 0,
        createdAt INTEGER,
        syncStatus TEXT DEFAULT 'synced',
        lastModified INTEGER
      )
    ''');

    // Materials table
    await db.execute('''
      CREATE TABLE materials(
        id TEXT PRIMARY KEY,
        name TEXT,
        category TEXT,
        unit TEXT,
        cost_per_unit REAL DEFAULT 0,
        stock INTEGER,
        minimumLevel INTEGER,
        createdAt INTEGER,
        syncStatus TEXT DEFAULT 'synced',
        lastModified INTEGER
      )
    ''');

    // Equipment table
    await db.execute('''
      CREATE TABLE equipment(
        id TEXT PRIMARY KEY,
        name TEXT,
        type TEXT,
        status TEXT,
        serialNumber TEXT,
        make TEXT,
        model TEXT,
        year INTEGER,
        licensePlate TEXT,
        color TEXT,
        registration_expiry INTEGER,
        insurance_policy TEXT,
        insurance_expiry INTEGER,
        assignedTo TEXT,
        notes TEXT,
        syncStatus TEXT DEFAULT 'synced',
        lastModified INTEGER
      )
    ''');

    // Customers table
    await db.execute('''
      CREATE TABLE customers(
        id TEXT PRIMARY KEY,
        name TEXT,
        phone TEXT,
        email TEXT,
        address TEXT,
        createdAt INTEGER,
        syncStatus TEXT DEFAULT 'synced',
        lastModified INTEGER
      )
    ''');

    // Suppliers table
    await db.execute('''
      CREATE TABLE suppliers(
        id TEXT PRIMARY KEY,
        name TEXT,
        phone TEXT,
        createdAt INTEGER,
        syncStatus TEXT DEFAULT 'synced',
        lastModified INTEGER
      )
    ''');

    // Supplier materials junction table
    await db.execute('''
      CREATE TABLE supplier_materials(
        id TEXT PRIMARY KEY,
        supplierId TEXT,
        materialId TEXT,
        notes TEXT,
        syncStatus TEXT DEFAULT 'synced',
        lastModified INTEGER
      )
    ''');

    // Properties table
    await db.execute('''
      CREATE TABLE properties(
        id TEXT PRIMARY KEY,
        name TEXT,
        address TEXT,
        type TEXT,
        ownership TEXT,
        usageType TEXT DEFAULT 'rented_out',
        rentalExpenseType TEXT,
        status TEXT DEFAULT 'vacant',
        monthlyRent REAL,
        landlordName TEXT,
        landlordPhone TEXT,
        mortgageBank TEXT,
        mortgageMonthly REAL,
        syncStatus TEXT DEFAULT 'synced',
        lastModified INTEGER
      )
    ''');

    // Tenants table
    await db.execute('''
      CREATE TABLE tenants(
        id TEXT PRIMARY KEY,
        propertyId TEXT,
        name TEXT,
        phone TEXT,
        monthlyRent REAL,
        createdAt INTEGER,
        syncStatus TEXT DEFAULT 'synced',
        lastModified INTEGER
      )
    ''');

    // Rent payments table
    await db.execute('''
      CREATE TABLE rent_payments(
        id TEXT PRIMARY KEY,
        tenantId TEXT,
        tenantName TEXT,
        amount REAL,
        month TEXT,
        paidAt INTEGER,
        syncStatus TEXT DEFAULT 'synced',
        lastModified INTEGER
      )
    ''');

    // Rent dues table
    await db.execute('''
      CREATE TABLE rent_dues(
        id TEXT PRIMARY KEY,
        tenantId TEXT,
        tenantName TEXT,
        propertyId TEXT,
        amount REAL,
        dueMonth TEXT,
        dueDate INTEGER,
        status TEXT,
        createdAt INTEGER,
        syncStatus TEXT DEFAULT 'synced',
        lastModified INTEGER
      )
    ''');

    await db.execute('''
      CREATE TABLE landlord_payments(
        id TEXT PRIMARY KEY,
        propertyId TEXT,
        landlordName TEXT,
        amount REAL,
        month TEXT,
        paidAt INTEGER,
        notes TEXT,
        syncStatus TEXT DEFAULT 'synced',
        lastModified INTEGER,
        changed_fields TEXT
      )
    ''');

    await db.execute('''
      CREATE TABLE landlord_dues(
        id TEXT PRIMARY KEY,
        propertyId TEXT,
        propertyName TEXT,
        landlordName TEXT,
        amount REAL,
        dueMonth TEXT,
        dueDate INTEGER,
        status TEXT,
        createdAt INTEGER,
        syncStatus TEXT DEFAULT 'synced',
        lastModified INTEGER,
        changed_fields TEXT
      )
    ''');

    // Social accounts table
    await db.execute('''
      CREATE TABLE social_accounts(
        id TEXT PRIMARY KEY,
        platform TEXT,
        accountName TEXT,
        accountUrl TEXT,
        employeeId TEXT,
        employeeName TEXT,
        syncStatus TEXT DEFAULT 'synced',
        lastModified INTEGER
      )
    ''');

    // Social metrics table
    await db.execute('''
      CREATE TABLE social_metrics(
        id TEXT PRIMARY KEY,
        accountId TEXT,
        date INTEGER,
        followers INTEGER,
        posts INTEGER,
        likes INTEGER,
        comments INTEGER,
        shares INTEGER,
        views INTEGER,
        syncStatus TEXT DEFAULT 'synced',
        lastModified INTEGER
      )
    ''');

    // Purchase orders table
    await db.execute('''
      CREATE TABLE purchase_orders(
        id TEXT PRIMARY KEY,
        supplierId TEXT,
        supplierName TEXT,
        orderDate INTEGER,
        expectedDate INTEGER,
        status TEXT,
        notes TEXT,
        totalAmount REAL,
        createdAt INTEGER,
        createdBy TEXT,
        syncStatus TEXT DEFAULT 'synced',
        lastModified INTEGER
      )
    ''');

    // Purchase order items table
    await db.execute('''
      CREATE TABLE purchase_order_items(
        id TEXT PRIMARY KEY,
        poId TEXT,
        itemType TEXT,
        itemId TEXT,
        itemName TEXT,
        quantity INTEGER,
        unitPrice REAL,
        syncStatus TEXT DEFAULT 'synced',
        lastModified INTEGER
      )
    ''');

    // Fuel logs table
    await db.execute('''
      CREATE TABLE fuel_logs(
        id TEXT PRIMARY KEY,
        vehicleId TEXT,
        date INTEGER,
        odometer INTEGER,
        liters REAL,
        cost REAL,
        notes TEXT,
        syncStatus TEXT DEFAULT 'synced',
        lastModified INTEGER
      )
    ''');

    // Maintenance logs table
    await db.execute('''
      CREATE TABLE maintenance_logs(
        id TEXT PRIMARY KEY,
        vehicleId TEXT,
        date INTEGER,
        type TEXT,
        description TEXT,
        cost REAL,
        odometer INTEGER,
        nextDue INTEGER,
        completed BOOLEAN,
        notes TEXT,
        syncStatus TEXT DEFAULT 'synced',
        lastModified INTEGER
      )
    ''');

    // Checkout logs table
    await db.execute('''
      CREATE TABLE checkout_logs(
        id TEXT PRIMARY KEY,
        equipmentId TEXT,
        equipmentName TEXT,
        employeeId TEXT,
        employeeName TEXT,
        checkoutDate INTEGER,
        expectedReturnDate INTEGER,
        actualReturnDate INTEGER,
        notes TEXT,
        syncStatus TEXT DEFAULT 'synced',
        lastModified INTEGER
      )
    ''');

    // Commissions table
    await db.execute('''
      CREATE TABLE commissions(
        id TEXT PRIMARY KEY,
        orderId TEXT,
        employeeId TEXT,
        employeeName TEXT,
        amount REAL,
        type TEXT,
        status TEXT DEFAULT 'pending',
        createdAt INTEGER,
        paidAt INTEGER,
        syncStatus TEXT DEFAULT 'synced',
        lastModified INTEGER
      )
    ''');

    // Conflicts table
    await db.execute('''
      CREATE TABLE conflicts(
        id TEXT PRIMARY KEY,
        tableName TEXT,
        recordId TEXT,
        localData TEXT,
        serverData TEXT,
        conflictingFields TEXT,
        timestamp INTEGER
      )
    ''');

    // Last sync table
    await db.execute('''
      CREATE TABLE last_sync(
        collection TEXT PRIMARY KEY,
        timestamp INTEGER
      )
    ''');

    // Measurement types table
    await db.execute('''
      CREATE TABLE measurement_types(
        id TEXT PRIMARY KEY,
        name TEXT,
        unit TEXT,
        sortOrder INTEGER,
        syncStatus TEXT DEFAULT 'synced',
        lastModified INTEGER
      )
    ''');

    // Measurements table
    await db.execute('''
      CREATE TABLE measurements(
        id TEXT PRIMARY KEY,
        customer_id TEXT,
        measurement_type_id TEXT,
        date_taken INTEGER,
        value REAL,
        notes TEXT,
        order_id TEXT,
        syncStatus TEXT DEFAULT 'synced',
        lastModified INTEGER
      )
    ''');

    // Accounts table
    await db.execute('''
      CREATE TABLE accounts(
        id TEXT PRIMARY KEY,
        name TEXT,
        type TEXT,
        opening_balance REAL,
        current_balance REAL,
        branchId TEXT,
        notes TEXT,
        syncStatus TEXT DEFAULT 'synced',
        lastModified INTEGER
      )
    ''');

    // Transactions table
    await db.execute('''
      CREATE TABLE transactions(
        id TEXT PRIMARY KEY,
        account_id TEXT,
        date INTEGER,
        amount REAL,
        type TEXT,
        category TEXT,
        reference_id TEXT,
        description TEXT,
        status TEXT,
        syncStatus TEXT DEFAULT 'synced',
        lastModified INTEGER
      )
    ''');

    // Production orders table
    await db.execute('''
      CREATE TABLE production_orders(
        id TEXT PRIMARY KEY,
        productName TEXT,
        tailorId TEXT,
        tailorName TEXT,
        materialsUsed TEXT,
        totalMaterialCost REAL,
        tailorCommission REAL,
        totalCost REAL,
        sellingPrice REAL DEFAULT 0,
        status TEXT,
        createdAt INTEGER,
        completedAt INTEGER,
        notes TEXT,
        syncStatus TEXT DEFAULT 'synced',
        lastModified INTEGER
      )
    ''');

    // Employee payments table
    await db.execute('''
      CREATE TABLE employee_payments(
        id TEXT PRIMARY KEY,
        employeeId TEXT,
        employeeName TEXT,
        type TEXT,
        amount REAL,
        month TEXT,
        for_month TEXT,
        status TEXT DEFAULT 'paid',
        datePaid INTEGER,
        createdAt INTEGER,
        notes TEXT,
        syncStatus TEXT DEFAULT 'synced',
        lastModified INTEGER
      )
    ''');

    // Leave requests table
    await db.execute('''
      CREATE TABLE leave_requests(
        id TEXT PRIMARY KEY,
        employeeId TEXT,
        employeeName TEXT,
        startDate INTEGER,
        endDate INTEGER,
        reason TEXT,
        status TEXT DEFAULT 'pending',
        approvedBy TEXT,
        approvedAt INTEGER,
        notes TEXT,
        syncStatus TEXT DEFAULT 'synced',
        lastModified INTEGER
      )
    ''');

    // Pending deletions table
    await db.execute('''
      CREATE TABLE pending_deletions(
        id TEXT PRIMARY KEY,
        tableName TEXT,
        recordId TEXT,
        timestamp INTEGER
      )
    ''');

    // Retail products table
    await db.execute('''
      CREATE TABLE IF NOT EXISTS retail_products(
        id TEXT PRIMARY KEY,
        name TEXT NOT NULL,
        description TEXT,
        category TEXT,
        costPrice REAL,
        sellingPrice REAL,
        stock INTEGER DEFAULT 0,
        minimumStock INTEGER DEFAULT 0,
        branchId TEXT,
        tailorId TEXT,
        tailorCommission REAL,
        createdAt INTEGER,
        syncStatus TEXT DEFAULT 'pending',
        lastModified INTEGER,
        changed_fields TEXT
      )
    ''');

    // Payment transaction table
    await db.execute('''
      CREATE TABLE payment_transaction(
        id TEXT PRIMARY KEY,
        orderId TEXT,
        branchId TEXT,
        receivedBy TEXT,
        date INTEGER,
        type TEXT,
        amount REAL DEFAULT 0,
        tip_amount REAL DEFAULT 0,
        deletedAt INTEGER DEFAULT 0,
        syncStatus TEXT DEFAULT 'synced',
        lastModified INTEGER
      )
    ''');

    // Payment breakdown table
    await db.execute('''
      CREATE TABLE payment_breakdown(
        id TEXT PRIMARY KEY,
        payment_transaction_id TEXT,
        method TEXT,
        amount REAL,
        account_id TEXT,
        syncStatus TEXT DEFAULT 'synced',
        lastModified INTEGER
      )
    ''');
    await db.execute('''
      CREATE TABLE material_usage(
        id TEXT PRIMARY KEY,
        material_id TEXT,
        quantity REAL,
        cost REAL,
        date INTEGER,
        notes TEXT,
        orderId TEXT,
        type TEXT DEFAULT 'order',
        syncStatus TEXT DEFAULT 'synced',
        lastModified INTEGER
      )
    ''');
    await db.execute('''
      CREATE TABLE losses(
        id TEXT PRIMARY KEY,
        date INTEGER,
        type TEXT,
        amount REAL,
        reason TEXT,
        orderId TEXT,
        syncStatus TEXT DEFAULT 'synced',
        lastModified INTEGER
      )
    ''');
    await db.execute('''
      CREATE TABLE IF NOT EXISTS dashboard_cache (
        key TEXT PRIMARY KEY,
        value TEXT,
        lastUpdated INTEGER
      )
    ''');

    await _ensureChangedFieldsColumns(db);
    await _ensureConflictColumns(db);
    await _seedDefaultRoles(db);
  }

  // ========== CRUD METHODS ==========
  Map<String, dynamic> _jsonSafeMap(Map<String, dynamic> data) {
    return Map<String, dynamic>.from(data);
  }

  Map<String, dynamic> _trackedFieldDiff(
    Map<String, dynamic> previous,
    Map<String, dynamic> next, {
    Set<String> exclude = const {},
  }) {
    final diff = <String, dynamic>{};
    final keys = {...previous.keys, ...next.keys};
    for (final key in keys) {
      if (_excludedChangedFields.contains(key) || exclude.contains(key)) {
        continue;
      }
      final previousValue = previous[key];
      final nextValue = next[key];
      if (previousValue != nextValue) {
        diff[key] = nextValue;
      }
    }
    return diff;
  }

  Future<Map<String, dynamic>?> _rowForUpdate(String table, dynamic id) async {
    if (id == null) return null;
    return await queryById(table, id.toString());
  }

  Future<Map<String, dynamic>?> _rowForInsert(String table, dynamic id) async {
    if (id == null) return null;
    return await queryById(table, id.toString());
  }

  Map<String, dynamic> _withWriteMetadata(
    Map<String, dynamic> data, {
    required bool markSynced,
    Map<String, dynamic>? changedFields,
  }) {
    final payload = _jsonSafeMap(data);
    payload['syncStatus'] = markSynced ? 'synced' : 'pending';
    payload['lastModified'] = DateTime.now().millisecondsSinceEpoch;
    if (changedFields != null) {
      payload['changed_fields'] = jsonEncode(changedFields);
    } else if (!payload.containsKey('changed_fields') &&
        payload.isNotEmpty &&
        payload['id'] != null) {
      final autoChanged = _trackedFieldDiff(const {}, payload);
      payload['changed_fields'] = jsonEncode(autoChanged);
    }
    return payload;
  }

  Future<String> insert(
    String table,
    Map<String, dynamic> data, {
    bool markSynced = false,
    Map<String, dynamic>? changedFields,
  }) async {
    Database db = await database;
    final record = Map<String, dynamic>.from(data);
    final rawId = record['id']?.toString().trim();
    if ((rawId == null || rawId.isEmpty) &&
        _autoGeneratedTextIdTables.contains(table)) {
      record['id'] = _uuid.v4();
    }
    final payload = _withWriteMetadata(
      record,
      markSynced: markSynced,
      changedFields: changedFields,
    );
    await db.insert(
      table,
      payload,
      conflictAlgorithm: ConflictAlgorithm.replace,
    );
    return payload['id']?.toString() ?? '';
  }

  Future<void> update(
    String table,
    Map<String, dynamic> data, {
    bool markSynced = false,
    Map<String, dynamic>? changedFields,
  }) async {
    Database db = await database;
    final current = await _rowForUpdate(table, data['id']);
    final merged = current == null
        ? Map<String, dynamic>.from(data)
        : <String, dynamic>{...current, ...data};
    final payload = _withWriteMetadata(
      merged,
      markSynced: markSynced,
      changedFields:
          changedFields ??
          (current == null
              ? _trackedFieldDiff(const {}, merged)
              : _trackedFieldDiff(current, merged)),
    );
    await db.update(table, payload, where: 'id = ?', whereArgs: [data['id']]);
  }

  Future<void> delete(String table, dynamic id) async {
    Database db = await database;
    final recordId = id.toString();
    // Insert into pending_deletions (replace if duplicate id exists)
    await db.insert(
      'pending_deletions',
      {
        'id': '${table}_$recordId',
        'tableName': table,
        'recordId': recordId,
        'timestamp': DateTime.now().millisecondsSinceEpoch,
      },
      conflictAlgorithm: ConflictAlgorithm.replace,
    );
    // Remove from main table
    await db.delete(table, where: 'id = ?', whereArgs: [id]);
  }

  bool _isSoftDeletedPayment(Map<String, dynamic> row) {
    final deletedAt = row['deletedAt'];
    if (deletedAt is num && deletedAt.toInt() > 0) return true;
    if (deletedAt is String && int.tryParse(deletedAt) != null) {
      return int.parse(deletedAt) > 0;
    }
    final isDeleted = row['isDeleted'];
    if (isDeleted is bool) return isDeleted;
    if (isDeleted is num) return isDeleted.toInt() != 0;
    if (isDeleted is String) {
      return isDeleted.toLowerCase() == 'true' || isDeleted == '1';
    }
    return false;
  }

  List<Map<String, dynamic>> _filterActivePayments(
    List<Map<String, dynamic>> rows,
  ) {
    return rows.where((row) => !_isSoftDeletedPayment(row)).toList();
  }

  Future<List<Map<String, dynamic>>> query(String table) async {
    Database db = await database;
    final results = await db.query(table);
    if (table == 'payment_transaction') {
      return _filterActivePayments(results);
    }
    if (table == 'orders') {
      return await _applyComputedPaidAmount(results);
    }
    return results;
  }

  Future<List<Map<String, dynamic>>> queryAll(String table) async {
    return query(table);
  }

  Future<Map<String, dynamic>?> queryById(String table, String id) async {
    Database db = await database;
    List<Map<String, dynamic>> results = await db.query(
      table,
      where: 'id = ?',
      whereArgs: [id],
    );
    if (results.isEmpty) return null;
    if (table == 'payment_transaction' && _isSoftDeletedPayment(results.first)) {
      return null;
    }
    if (table == 'orders') {
      final computed = await _applyComputedPaidAmount([results.first]);
      return computed.isNotEmpty ? computed.first : results.first;
    }
    return results.first;
  }

  Future<Map<String, dynamic>?> getRoleByName(String name) async {
    final results = await queryWhere('roles', 'name = ?', [name]);
    if (results.isEmpty) return null;
    return results.first;
  }

  Future<Map<String, dynamic>?> getRoleById(int id) async {
    final db = await database;
    final results = await db.query('roles', where: 'id = ?', whereArgs: [id]);
    if (results.isEmpty) return null;
    return results.first;
  }

  Future<void> insertStatusLog({
    required String orderId,
    required String newStatus,
    required String changedBy,
    required int changedAt,
    String? note,
  }) async {
    await insert('order_status_logs', {
      'orderId': orderId,
      'status': newStatus,
      'changedBy': changedBy,
      'changedAt': changedAt,
      'note': note,
      'lastModified': changedAt,
    });
  }

  Future<List<Map<String, dynamic>>> getStatusLogsForOrder(String orderId) async {
    final rows = await queryWhere('order_status_logs', 'orderId = ?', [orderId]);
    rows.sort(
      (a, b) => ((b['changedAt'] as num?)?.toInt() ?? 0).compareTo(
        (a['changedAt'] as num?)?.toInt() ?? 0,
      ),
    );
    return rows;
  }

  Future<List<Map<String, dynamic>>> queryWhere(
    String table,
    String whereClause,
    List<dynamic> whereArgs,
  ) async {
    Database db = await database;
    final results = await db.query(
      table,
      where: whereClause,
      whereArgs: whereArgs,
    );
    if (table == 'payment_transaction') {
      return _filterActivePayments(results);
    }
    if (table == 'orders') {
      return await _applyComputedPaidAmount(results);
    }
    return results;
  }

  Future<void> increaseProductStock(String productId, int quantity) async {
    if (quantity <= 0) return;
    final product = await queryById('products', productId);
    if (product == null) {
      throw Exception('Product not found');
    }
    final updatedProduct = Map<String, dynamic>.from(product);
    final currentStock = (updatedProduct['stock'] as num?)?.toInt() ?? 0;
    updatedProduct['stock'] = currentStock + quantity;
    await update('products', updatedProduct);
  }

  Future<List<Map<String, dynamic>>> getOrdersInDateRange(
    int startMillis,
    int endMillis, {
    String? branchId,
  }) async {
    final db = await database;
    var sql = 'SELECT * FROM orders WHERE createdAt BETWEEN ? AND ?';
    final args = <Object?>[startMillis, endMillis];
    if (branchId != null) {
      sql += ' AND branchId = ?';
      args.add(branchId);
    }
    final results = await db.rawQuery(sql, args);
    return _applyComputedPaidAmount(results);
  }

  Future<List<Map<String, dynamic>>> getPaymentsInDateRange(
    int startMillis,
    int endMillis, {
    String? branchId,
  }) async {
    final db = await database;
    var sql = '''
      SELECT pt.* FROM payment_transaction pt
      JOIN orders o ON pt.orderId = o.id
      WHERE pt.date BETWEEN ? AND ?
      AND COALESCE(pt.deletedAt, 0) = 0
    ''';
    final args = <Object?>[startMillis, endMillis];
    if (branchId != null) {
      sql += ' AND o.branchId = ?';
      args.add(branchId);
    }
    return db.rawQuery(sql, args);
  }

  Future<List<Map<String, dynamic>>> getCommissionsInDateRange(
    int startMillis,
    int endMillis, {
    String? branchId,
  }) async {
    final db = await database;
    var sql = '''
      SELECT c.* FROM commissions c
      JOIN orders o ON c.orderId = o.id
      WHERE ((c.createdAt BETWEEN ? AND ?) OR (c.paidAt BETWEEN ? AND ?))
    ''';
    final args = <Object?>[startMillis, endMillis, startMillis, endMillis];
    if (branchId != null) {
      sql += ' AND o.branchId = ?';
      args.add(branchId);
    }
    return db.rawQuery(sql, args);
  }

  Future<List<Map<String, dynamic>>> getFuelLogsInDateRange(
    int startMillis,
    int endMillis,
  ) async {
    final db = await database;
    return db.rawQuery('SELECT * FROM fuel_logs WHERE date BETWEEN ? AND ?', [
      startMillis,
      endMillis,
    ]);
  }

  Future<List<Map<String, dynamic>>> getMaintenanceLogsInDateRange(
    int startMillis,
    int endMillis,
  ) async {
    final db = await database;
    return db.rawQuery(
      'SELECT * FROM maintenance_logs WHERE date BETWEEN ? AND ?',
      [startMillis, endMillis],
    );
  }

  Future<List<Map<String, dynamic>>> getMaterialUsageInDateRange(
    int startMillis,
    int endMillis,
  ) async {
    final db = await database;
    return db.rawQuery(
      'SELECT * FROM material_usage WHERE date BETWEEN ? AND ?',
      [startMillis, endMillis],
    );
  }

  Future<List<Map<String, dynamic>>> getLossesInDateRange(
    int startMillis,
    int endMillis, {
    String? branchId,
  }) async {
    final db = await database;
    var sql = 'SELECT * FROM losses WHERE date BETWEEN ? AND ?';
    final args = <Object?>[startMillis, endMillis];
    if (branchId != null) {
      sql += ' AND branchId = ?';
      args.add(branchId);
    }
    return db.rawQuery(sql, args);
  }

  Future<List<Map<String, dynamic>>> getLandlordPaymentsInDateRange(
    int startMillis,
    int endMillis,
  ) async {
    final db = await database;
    return db.query(
      'landlord_payments',
      where: 'paidAt BETWEEN ? AND ?',
      whereArgs: [startMillis, endMillis],
    );
  }

  Future<List<Map<String, dynamic>>> _applyComputedPaidAmount(
    List<Map<String, dynamic>> orders,
  ) async {
    if (orders.isEmpty) return orders;
    final payments = await query('payment_transaction');
    final paymentTotals = <String, double>{};
    for (final payment in payments) {
      final orderId = payment['orderId']?.toString();
      if (orderId == null || orderId.isEmpty) continue;
      final amount = (payment['amount'] as num?)?.toDouble() ?? 0.0;
      final type = payment['type']?.toString();
      if (type == 'refund') {
        paymentTotals[orderId] = (paymentTotals[orderId] ?? 0.0) - amount;
      } else {
        paymentTotals[orderId] = (paymentTotals[orderId] ?? 0.0) + amount;
      }
    }

    return orders.map((order) {
      final orderCopy = Map<String, dynamic>.from(order);
      final orderId = orderCopy['id']?.toString();
      final totalAmount = (orderCopy['totalAmount'] as num?)?.toDouble() ?? 0.0;
      final storedPaid = (orderCopy['paid_amount'] as num?)?.toDouble() ?? 0.0;
      final computedPaid = orderId == null
          ? 0.0
          : (paymentTotals[orderId] ?? 0.0);
      final resolvedPaid = paymentTotals.containsKey(orderId)
          ? computedPaid
          : storedPaid;
      orderCopy['paid_amount'] = resolvedPaid.clamp(0.0, totalAmount);
      return orderCopy;
    }).toList();
  }

  Future<List<Map<String, dynamic>>> getPendingRecords(String table) async {
    Database db = await database;
    return await db.query(
      table,
      where: 'syncStatus = ?',
      whereArgs: ['pending'],
    );
  }

  Future<List<Map<String, dynamic>>> generateMonthlySalaries(
    String monthKey,
  ) async {
    final db = await database;
    final employees = await db.rawQuery(
      '''
      SELECT u.id, u.name, u.monthly_salary
      FROM users u
      JOIN roles r ON u.role_id = r.id
      WHERE r.salary_type = 'monthly'
        AND u.status = 'active'
        AND u.monthly_salary IS NOT NULL
        AND u.id NOT IN (
          SELECT employeeId FROM employee_payments
          WHERE type = 'salary' AND for_month = ?
        )
      ''',
      [monthKey],
    );

    final now = DateTime.now().millisecondsSinceEpoch;
    for (final emp in employees) {
      await insert('employee_payments', {
        'id': '${emp['id']}_salary_$monthKey',
        'employeeId': emp['id']?.toString(),
        'employeeName': emp['name']?.toString(),
        'type': 'salary',
        'amount': (emp['monthly_salary'] as num?)?.toDouble() ?? 0.0,
        'month': monthKey,
        'for_month': monthKey,
        'status': 'pending',
        'datePaid': now,
        'createdAt': now,
        'notes': 'Generated salary for $monthKey',
      });
    }

    return employees.map((emp) => Map<String, dynamic>.from(emp)).toList();
  }

  Future<void> markAsSynced(String table, String id) async {
    Database db = await database;
    await db.update(
      table,
      {'syncStatus': 'synced'},
      where: 'id = ?',
      whereArgs: [id],
    );
  }

  // ========== CONFLICT METHODS ==========
  Future<void> insertConflict(Map<String, dynamic> conflict) async {
    Database db = await database;
    await db.insert(
      'conflicts',
      conflict,
      conflictAlgorithm: ConflictAlgorithm.replace,
    );
  }

  Future<List<Map<String, dynamic>>> getConflicts() async {
    Database db = await database;
    return await db.query('conflicts', orderBy: 'timestamp DESC');
  }

  Future<void> deleteConflict(String id) async {
    Database db = await database;
    await db.delete('conflicts', where: 'id = ?', whereArgs: [id]);
  }

  Future<void> clearConflicts() async {
    Database db = await database;
    await db.delete('conflicts');
  }

  Future<void> saveCache(String key, Map<String, dynamic> data) async {
    Database db = await database;
    await db.insert('dashboard_cache', {
      'key': key,
      'value': jsonEncode(data),
      'lastUpdated': DateTime.now().millisecondsSinceEpoch,
    }, conflictAlgorithm: ConflictAlgorithm.replace);
  }

  Future<Map<String, dynamic>?> loadCache(String key) async {
    Database db = await database;
    final res = await db.query(
      'dashboard_cache',
      where: 'key = ?',
      whereArgs: [key],
    );
    if (res.isEmpty) return null;
    final value = res.first['value'];
    if (value is! String || value.isEmpty) return null;
    final decoded = jsonDecode(value);
    if (decoded is Map<String, dynamic>) return decoded;
    if (decoded is Map) {
      return Map<String, dynamic>.from(decoded);
    }
    return null;
  }

  // ========== LAST SYNC METHODS ==========
  Future<int?> getLastSync(String collection) async {
    Database db = await database;
    List<Map<String, dynamic>> results = await db.query(
      'last_sync',
      where: 'collection = ?',
      whereArgs: [collection],
    );
    return results.isNotEmpty ? results.first['timestamp'] as int? : null;
  }

  Future<void> setLastSync(String collection, int timestamp) async {
    Database db = await database;
    await db.insert('last_sync', {
      'collection': collection,
      'timestamp': timestamp,
    }, conflictAlgorithm: ConflictAlgorithm.replace);
  }

  // ========== BATCH OPERATIONS ==========
  Future<void> insertBatch(
    String table,
    List<Map<String, dynamic>> dataList,
  ) async {
    Database db = await database;
    await db.transaction((txn) async {
      for (var data in dataList) {
        final payload = _withWriteMetadata(data, markSynced: false);
        await txn.insert(
          table,
          payload,
          conflictAlgorithm: ConflictAlgorithm.replace,
        );
      }
    });
  }

  // ========== METHOD FOR LAST SYNC TIMESTAMP ==========
  Future<int?> getLatestSyncTime() async {
    Database db = await database;
    List<Map<String, dynamic>> results = await db.query(
      'last_sync',
      orderBy: 'timestamp DESC',
      limit: 1,
    );
    return results.isNotEmpty ? results.first['timestamp'] as int? : null;
  }

  // ========== PENDING DELETIONS (optional direct access) ==========
  Future<List<Map<String, dynamic>>> getPendingDeletions() async {
    Database db = await database;
    return await db.query('pending_deletions');
  }

  Future<Map<String, dynamic>?> getUser(String id) async {
    return await queryById('users', id);
  }

  Future<Map<String, dynamic>?> getBranchById(String id) async {
    return await queryById('branches', id);
  }

  Future<Map<String, dynamic>?> getCashAccountForBranch(String? branchId) async {
    final db = await database;
    List<Map<String, dynamic>> rows = [];
    if (branchId != null) {
      rows = await db.query(
        'accounts',
        where: "type = ? AND branchId = ?",
        whereArgs: ['cash', branchId],
        limit: 1,
      );
    }
    if (rows.isEmpty) {
      rows = await db.query(
        'accounts',
        where: "type = ?",
        whereArgs: ['cash'],
        limit: 1,
      );
    }
    return rows.isNotEmpty ? rows.first : null;
  }

  Future<void> clearPendingDeletion(String id) async {
    Database db = await database;
    await db.delete('pending_deletions', where: 'id = ?', whereArgs: [id]);
  }

  Future<void> addPayment(
    String orderId,
    double amount,
    String method, {
    String type = 'payment',
    String? branchId,
    String? receivedBy,
    required String accountId,
  }) async {
    if (amount <= 0) {
      throw Exception('Amount must be greater than zero');
    }

    final account = await queryById('accounts', accountId);
    if (account == null) {
      throw Exception('Account not found');
    }

    final order = await queryById('orders', orderId);
    if (order == null) {
      throw Exception('Order not found');
    }

    final currentPaid = (order['paid_amount'] as num?)?.toDouble() ?? 0.0;
    final orderTotal = (order['totalAmount'] as num?)?.toDouble() ?? 0.0;

    double newPaid = currentPaid + amount;
    double tipAmount = 0.0;
    if (type == 'refund') {
      if (amount > currentPaid) {
        throw Exception('Refund cannot exceed paid amount');
      }
      newPaid = currentPaid - amount;
    } else if (newPaid > orderTotal) {
      tipAmount = newPaid - orderTotal;
      newPaid = orderTotal;
    }

    final transactionId = await insert('payment_transaction', {
      'orderId': orderId,
      'branchId': branchId ?? order['branchId'],
      'receivedBy': receivedBy,
      'date': DateTime.now().millisecondsSinceEpoch,
      'type': type,
      'amount': amount,
      'tip_amount': tipAmount,
      'deletedAt': 0,
    });
    await insert('payment_breakdown', {
      'id': '${transactionId}_$method',
      'payment_transaction_id': transactionId,
      'method': method,
      'amount': amount,
      'account_id': accountId,
    });
    await _updateAccountBalance(accountId, amount, type);
    await update('orders', {'id': orderId, 'paid_amount': newPaid});
  }

  Future<void> _updateAccountBalance(
    String accountId,
    double amount,
    String type,
  ) async {
    final account = await queryById('accounts', accountId);
    if (account == null) {
      throw Exception('Account not found');
    }
    final currentBalance =
        (account['current_balance'] as num?)?.toDouble() ?? 0.0;
    final newBalance = type == 'refund'
        ? currentBalance - amount
        : currentBalance + amount;
    await update('accounts', {'id': accountId, 'current_balance': newBalance});
  }

  Future<List<Map<String, dynamic>>> getPaymentsForOrder(String orderId) async {
    final db = await database;
    final rawPayments = List<Map<String, dynamic>>.from(
      await db.rawQuery(
        '''
        SELECT
          pt.*,
          pb.method AS method,
          pb.account_id AS accountId
        FROM payment_transaction pt
        LEFT JOIN payment_breakdown pb
          ON pb.payment_transaction_id = pt.id
        WHERE pt.orderId = ?
        ORDER BY pt.date DESC
        ''',
        [orderId],
      ),
    );
    final activePayments = _filterActivePayments(rawPayments);
    // Order details should favor complete transaction history. If every row is
    // filtered out by soft-delete flags, fall back to the raw rows so genuine
    // payment/refund history does not disappear.
    final payments = activePayments.isNotEmpty ? activePayments : rawPayments;
    payments.sort(
      (a, b) => ((b['date'] as num?)?.toInt() ?? 0).compareTo(
        (a['date'] as num?)?.toInt() ?? 0,
      ),
    );
    return payments;
  }

  Future<void> clearPaymentsForOrder(String orderId) async {
    final db = await database;
    final payments = await getPaymentsForOrder(orderId);
    await db.transaction((txn) async {
      for (final payment in payments) {
        final breakdowns = await txn.query(
          'payment_breakdown',
          where: 'payment_transaction_id = ?',
          whereArgs: [payment['id']],
        );
        for (final breakdown in breakdowns) {
          final accountId = await _resolveAccountForPaymentDeletion(
            txn,
            payment,
            breakdown,
          );
          if (accountId != null) {
            final accountRows = await txn.query(
              'accounts',
              where: 'id = ?',
              whereArgs: [accountId],
            );
            if (accountRows.isNotEmpty) {
              final currentBalance =
                  (accountRows.first['current_balance'] as num?)?.toDouble() ??
                  0.0;
              final amount = (breakdown['amount'] as num?)?.toDouble() ?? 0.0;
              final paymentType = payment['type']?.toString();
              final reversedBalance = paymentType == 'refund'
                  ? currentBalance + amount
                  : currentBalance - amount;
              await txn.update(
                'accounts',
                {'current_balance': reversedBalance},
                where: 'id = ?',
                whereArgs: [accountId],
              );
            }
          }
        }
        await txn.update(
          'payment_transaction',
          {
            'id': payment['id'],
            'deletedAt': DateTime.now().millisecondsSinceEpoch,
            'syncStatus': 'pending',
            'lastModified': DateTime.now().millisecondsSinceEpoch,
          },
          where: 'id = ?',
          whereArgs: [payment['id']],
        );
      }
      await txn.update(
        'orders',
        {
          'paid_amount': 0,
          'syncStatus': 'pending',
          'lastModified': DateTime.now().millisecondsSinceEpoch,
        },
        where: 'id = ?',
          whereArgs: [orderId],
      );
    });
  }

  Future<void> softDeletePayment(String paymentId) async {
    await update(
      'payment_transaction',
      {
        'id': paymentId,
        'deletedAt': DateTime.now().millisecondsSinceEpoch,
      },
    );
  }

  Future<String?> _resolveAccountForPaymentDeletion(
    DatabaseExecutor executor,
    Map<String, dynamic> payment,
    Map<String, dynamic> breakdown,
  ) async {
    final storedAccountId = breakdown['account_id']?.toString();
    if (storedAccountId != null && storedAccountId.isNotEmpty) {
      return storedAccountId;
    }

    final method = breakdown['method']?.toString();
    if (method == null || method.isEmpty) return null;

    final branchId = payment['branchId']?.toString();
    final accounts = await executor.query('accounts');
    final matches = accounts.where((account) {
      final accountType = account['type']?.toString();
      final accountBranchId = account['branchId']?.toString();
      if (method == 'cash') {
        return accountType == 'cash' && accountBranchId == branchId;
      }
      return accountType == 'bank' &&
          (accountBranchId == null || accountBranchId.isEmpty);
    }).toList();

    if (matches.isEmpty) return null;
    return matches.first['id']?.toString();
  }

  // New helper method for sales commission calculation
  Future<double> getNonSalesCommissionsForOrder(String orderId) async {
    final db = await database;
    final result = await db.rawQuery(
      'SELECT COALESCE(SUM(commission_amount), 0) AS total FROM order_assignments WHERE orderId = ? AND role != ?',
      [orderId, 'sales'],
    );
    return (result.first['total'] as num?)?.toDouble() ?? 0.0;
  }

  // Get total commissions for an order from the commissions table
  Future<double> getCommissionsTotalForOrder(String orderId) async {
    final db = await database;
    final result = await db.rawQuery(
      'SELECT COALESCE(SUM(amount), 0) AS total FROM commissions WHERE orderId = ?',
      [orderId],
    );
    return (result.first['total'] as num?)?.toDouble() ?? 0.0;
  }
}
